[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Скорость загрузки
upload_speed = 921600
monitor_speed = 115200

; Размер файловой системы для SPIFFS
board_build.partitions = min_spiffs.csv

; Библиотеки
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    esphome/ESPAsyncWebServer-esphome @ ^3.0.0
    mathieucarbou/AsyncTCP @ ^3.1.4
    adafruit/Adafruit SSD1306 @ ^2.5.10
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^7.0.0

; Флаги компиляции
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ; I2S пины
    -DI2S_BCLK=4
    -DI2S_LRC=5
    -DI2S_DOUT=6
    ; I2C пины (OLED)
    -DI2C_SDA=8
    -DI2C_SCL=9
